import type { Theme } from ".";

export const carNightTheme: Theme = {
  id: "car-night",
  name: "Závody aut — Noc",
  description: "Tmavý vzhled, noční závodní okruh, automobilové závody.",
  isPaid: false,
  priceCzk: 0,
  colors: {
    pageBackground:     "bg-slate-950",
    cardBackground:     "bg-slate-800",
    boardSurface:       "bg-slate-700",
    boardSurfaceBorder: "border-slate-600",
    centerBackground:   "bg-stone-950",
    centerBorder:       "border-stone-700",
    centerTitle:        "text-slate-200",
    centerSubtitle:     "text-slate-400",
    fieldStyles: {
      start:      "h-20 w-20 border-red-500 bg-red-800 text-white",
      coins_gain: "h-[72px] w-[72px] border-emerald-500 bg-emerald-900 text-emerald-300",
      coins_lose: "h-[72px] w-[72px] border-red-600 bg-red-950 text-red-300",
      gamble:     "h-[72px] w-[72px] border-violet-500 bg-violet-900 text-violet-300",
      racer:      "h-[72px] w-[72px] border-sky-500 bg-sky-900 text-sky-300",
      horse:      "h-[72px] w-[72px] border-sky-500 bg-sky-900 text-sky-300", // @deprecated alias
      neutral:    "h-[72px] w-[72px] border-slate-600 bg-slate-700 text-slate-300",
      chance:     "h-[72px] w-[72px] border-amber-500 bg-amber-900 text-amber-300",
      finance:    "h-[72px] w-[72px] border-teal-500 bg-teal-900 text-teal-300",
    },
    activePlayerBadge: "bg-sky-400 text-slate-900",
    rollPanelIdle:     "bg-slate-700",
    rollPanelRolling:  "bg-sky-950",
    textPrimary:       "text-slate-100",
    textMuted:         "text-slate-400",
    playerCardActive:  "border-sky-400 bg-slate-700 shadow-sm",
    playerCardNormal:  "border-slate-600 bg-slate-700",
    playerCardHover:   "border-sky-400 bg-slate-600 shadow-sm",
  },
  labels: {
    themeName:      "Závody aut — Noc",
    centerTitle:    "Závodiště",
    centerSubtitle: "Připravte motory.",
    legend: {
      gain:   "zisk",
      lose:   "ztráta",
      gamble: "hazard",
      horse:  "auto",
    },
    racer:      "Auto",
    racers:     "Auta",
    racerField: "Garáž",
  },
  racers: [
    { id: "stary_mustang",  name: "Starý Mustang",  speed: 2, price: 80,  emoji: "🚗" },
    { id: "modra_strela",   name: "Modrá střela",   speed: 3, price: 150, emoji: "🏎️" },
    { id: "zlaty_blesk",    name: "Zlatý blesk",    speed: 4, price: 250, emoji: "🟡" },
    { id: "rychly_demon",   name: "Rychlý démon",   speed: 5, price: 400, emoji: "🔥" },
  ],
};
