import type { Theme } from ".";

export const darkTheme: Theme = {
  id: "dark",
  name: "Noční závody",
  description: "Tmavý vzhled pro noční herní session.",
  isPaid: false,
  priceCzk: 0,
  colors: {
    pageBackground:     "bg-slate-950",
    cardBackground:     "bg-slate-800",
    boardSurface:       "bg-slate-700",
    boardSurfaceBorder: "border-slate-600",
    centerBackground:   "bg-slate-800",
    centerBorder:       "border-slate-500",
    centerTitle:        "text-slate-200",
    centerSubtitle:     "text-slate-400",
    fieldStyles: {
      start:      "h-20 w-20 border-red-500 bg-red-800 text-white",
      coins_gain: "h-16 w-16 border-emerald-500 bg-emerald-900 text-emerald-300",
      coins_lose: "h-16 w-16 border-red-600 bg-red-950 text-red-300",
      gamble:     "h-16 w-16 border-violet-500 bg-violet-900 text-violet-300",
      horse:      "h-16 w-16 border-amber-500 bg-amber-900 text-amber-300",
      neutral:    "h-16 w-16 border-slate-600 bg-slate-700 text-slate-300",
      chance:     "h-16 w-16 border-sky-500 bg-sky-900 text-sky-300",
      finance:    "h-16 w-16 border-teal-500 bg-teal-900 text-teal-300",
    },
    activePlayerBadge: "bg-amber-400 text-slate-900",
    rollPanelIdle:     "bg-slate-700",
    rollPanelRolling:  "bg-amber-950",
    textPrimary:       "text-slate-100",
    textMuted:         "text-slate-400",
    playerCardActive:  "border-amber-400 bg-slate-700 shadow-sm",
    playerCardNormal:  "border-slate-600 bg-slate-700",
    playerCardHover:   "border-blue-400 bg-slate-600 shadow-sm",
  },
  labels: {
    themeName:      "Noční závody",
    centerTitle:    "Dostihiště",
    centerSubtitle: "Přijdou závody.",
  },
  horses: [
    { id: "divoka_ruze",  name: "Divoká růže",  speed: 2, price: 80,  emoji: "🌹" },
    { id: "modry_blesk",  name: "Modrý blesk",  speed: 3, price: 150, emoji: "🔵" },
    { id: "zlata_hriva",  name: "Zlatá hříva",  speed: 4, price: 250, emoji: "🟡" },
    { id: "rychly_vitr",  name: "Rychlý vítr",  speed: 5, price: 400, emoji: "🟢" },
  ],
};
