import type { Theme } from ".";

export const horseNightTheme: Theme = {
  id: "horse-night",
  name: "Dostihy — Noc",
  description: "Tmavý vzhled, koňské dostihy za noci.",
  isPaid: false,
  priceCzk: 0,
  cardThemeTag: "horse",
  colors: {
    pageBackground:     "bg-slate-950",
    cardBackground:     "bg-slate-800",
    boardSurface:       "bg-slate-700/80",
    boardSurfaceBorder: "border-slate-600",
    centerBackground:   "bg-transparent",
    centerBorder:       "border-green-800/0",
    centerTitle:        "text-slate-200",
    centerSubtitle:     "text-slate-400",
    fieldStyles: {
      start:      "h-20 w-20 border-red-500 bg-red-800 text-white",
      coins_gain: "h-[72px] w-[72px] border-emerald-500 bg-emerald-900 text-emerald-300",
      coins_lose: "h-[72px] w-[72px] border-red-600 bg-red-950 text-red-300",
      gamble:     "h-[72px] w-[72px] border-violet-500 bg-violet-900 text-violet-300",
      racer:      "h-[72px] w-[72px] border-amber-500 bg-amber-900 text-amber-300",
      horse:      "h-[72px] w-[72px] border-amber-500 bg-amber-900 text-amber-300", // @deprecated alias
      neutral:    "h-[72px] w-[72px] border-slate-600 bg-slate-700 text-slate-300",
      chance:     "h-[72px] w-[72px] border-sky-500 bg-sky-900 text-sky-300",
      finance:    "h-[72px] w-[72px] border-sky-500 bg-teal-900 text-teal-300",
      mafia:     "h-[72px] w-[72px] border-purple-500 bg-purple-900 text-purple-300",
    },
    activePlayerBadge: "bg-amber-400 text-slate-900",
    rollPanelIdle:     "bg-slate-700",
    rollPanelRolling:  "bg-amber-950",
    textPrimary:       "text-slate-100",
    textMuted:         "text-slate-400",
    playerCardActive:  "border-amber-400 bg-slate-700 shadow-sm",
    playerCardNormal:  "border-slate-600 bg-slate-700",
    playerCardHover:   "border-blue-400 bg-slate-600 shadow-sm",
    arenaGradient:     "url('/horse-night.webp') center / cover no-repeat",
  },
  labels: {
    themeName:      "Dostihy — Noc",
    centerTitle:    "Noční závody",
    centerSubtitle: "Soukromá akce!",
    legend: {
      gain:   "zisk",
      lose:   "ztráta",
      gamble: "hazard",
      racer:  "kůň",
    },
    racer:       "Kůň",
    racers:      "Koně",
    racerField:  "Stáj",
    racingEmoji: "🐎",
  },
  racerRefs: [
    { slotIndex: 0, racer_id: "divoka_ruze" },
    { slotIndex: 1, racer_id: "viento_dorado" },
    { slotIndex: 2, racer_id: "zlata_hriva" },
    { slotIndex: 3, racer_id: "rychly_vitr" },
    { slotIndex: 4, racer_id: "horse_night_buran" },
  ],
  /** @fallback inline data — seed source + runtime fallback pokud registry není dostupná */
  racers: [
    {
      "id": "divoka_ruze",
      "name": "Mariane DR",
      "speed": 2,
      "price": 1200,
      "emoji": "🌹",
      "maxStamina": 100,
      "flavorText": "Nějaká kůň musí být nejlevnější.",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/divoka_ruze.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 0
    },
    {
      "id": "zlata_hriva",
      "name": "Goldie",
      "speed": 6,
      "price": 3000,
      "emoji": "🟡",
      "maxStamina": 90,
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/zlata_hriva.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 2
    },
    {
      "id": "rychly_vitr",
      "name": "Razor Wind",
      "speed": 9,
      "price": 4000,
      "emoji": "🟢",
      "maxStamina": 80,
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 3
    },
    {
      "id": "horse_night_buran",
      "name": "Burano",
      "speed": 7,
      "price": 5000,
      "emoji": "🐴",
      "maxStamina": 95,
      "flavorText": "Masivní černý kůň, který vítězí silou a výdrží spíš než rychlým startem.",
      "image": "/themes/_shared/racer-horse_night_buran.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 4
    },
    {
      "id": "caballo_real",
      "name": "Caballo Real",
      "speed": 5,
      "price": 3500,
      "emoji": "👑",
      "maxStamina": 100,
      "flavorText": "Kůň s královskou výdrží.",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/caballo_real.webp",
      "racerType": "horse",
      "slotIndex": 4
    },
    {
      "id": "viento_dorado",
      "name": "Hogo fogo",
      "speed": 3,
      "price": 1500,
      "emoji": "🟤",
      "maxStamina": 100,
      "flavorText": "Umí zabrat, ale i shodit jezdce!",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/viento_dorado.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 1
    },
    {
      "id": "zeleznik",
      "name": "Železník",
      "speed": 10,
      "price": 99999,
      "emoji": "🐴",
      "maxStamina": 10,
      "isLegendary": true,
      "flavorText": "Železník — legendární kůň, který nezná strach, únavu ani druhé místo. Jeho jediný cíl je jasný: vyhrát.",
      "image": "/themes/_shared/racer-zeleznik.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 7
    }
  ],
  assets: {
    boardBgImage: "/horse-night.webp",
    centerBgImage: "/plaketa-dark-rectangle.webp",
  },
  mapMeta: {
    yearStart: 1921,
    place: "New Orleans",
    subtitle: "Oficiálně klid. Neoficiálně se dnes sází ve velkém.",
  },
};
