import type { Theme } from ".";

export const horseClassicTheme: Theme = {
  id: "horse-classic",
  name: "Velká Chuchle",
  description: "Závodní dráha Velké Chuchle, rok 1921. Tradice, trávník a koňský osud.",
  isPaid: false,
  priceCzk: 0,
  cardThemeTag: "horse",
  colors: {
    pageBackground:     "bg-amber-50",
    cardBackground:     "bg-amber-50",
    boardSurface:       "bg-green-700/80",
    boardSurfaceBorder: "border-green-900",
    centerBackground:   "bg-green-800",
    centerBorder:       "border-green-600",
    centerTitle:        "text-amber-200",
    centerSubtitle:     "text-green-300",
    fieldStyles: {
      start:      "h-20 w-20 border-emerald-900 bg-emerald-800 text-amber-200",
      coins_gain: "h-[72px] w-[72px] border-green-600 bg-amber-100 text-green-900",
      coins_lose: "h-[72px] w-[72px] border-red-400 bg-red-100 text-red-900",
      gamble:     "h-[72px] w-[72px] border-purple-500 bg-purple-100 text-purple-900",
      racer:      "h-[72px] w-[72px] border-amber-600 bg-amber-200 text-amber-900",
      horse:      "h-[72px] w-[72px] border-amber-600 bg-amber-200 text-amber-900",
      neutral:    "h-[72px] w-[72px] border-stone-400 bg-stone-100 text-stone-700",
      chance:     "h-[72px] w-[72px] border-green-600 bg-green-100 text-green-900",
      finance:    "h-[72px] w-[72px] border-amber-600 bg-amber-100 text-amber-900",
      mafia:      "h-[72px] w-[72px] border-stone-500 bg-stone-200 text-stone-800",
    },
    activePlayerBadge: "bg-green-900 text-amber-200",
    rollPanelIdle:     "bg-amber-100",
    rollPanelRolling:  "bg-green-100",
    textPrimary:       "text-stone-800",
    textMuted:         "text-stone-500",
    playerCardActive:  "border-green-700 bg-green-50 shadow-sm",
    playerCardNormal:  "border-stone-300 bg-amber-50",
    playerCardHover:   "border-amber-500 bg-amber-100 shadow-sm",
    arenaGradient:     "radial-gradient(ellipse 140% 90% at 50% 50%, #f0fdf4 0%, #dcfce7 30%, #d1fae5 60%, #bbf7d0 100%)",
  },
  labels: {
    themeName:      "Velká Chuchle",
    centerTitle:    "Velká Chuchle",
    centerSubtitle: "Praha, 1921. Kdo má nejlepšího koně?",
    legend: {
      gain:   "Dostihový bonus",
      lose:   "Výdaj stáje",
      gamble: "Sázka",
      racer:  "Kůň",
    },
    racer:       "Kůň",
    racers:      "Koně",
    racerField:  "Stáj",
    racingEmoji: "🐎",
  },
  board: {
    id: "small-stadium",
    shape: "stadium",
    fieldCount: 21,
    racerSlotIndexes: [3, 10, 17, 19],
    fields: [
      { index: 0,  type: "start",      label: "Start / Cíl",         emoji: "🏁",  amount: 2000 },
      { index: 1,  type: "mafia",      label: "Záhadný mecenáš",     emoji: "🎩",  amount: 50 },
      { index: 2,  type: "coins_lose", label: "Veterinář",           emoji: "🩺",  amount: -600 },
      { index: 3,  type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 4,  type: "coins_gain", label: "Vítěz dostihu",       emoji: "🏆",  amount: 1500 },
      { index: 5,  type: "coins_lose", label: "Závodní poplatky",    emoji: "🏛️",  amount: -800 },
      { index: 6,  type: "coins_gain", label: "Zlaté podkůvky",      emoji: "🥇",  amount: 800 },
      { index: 7,  type: "coins_lose", label: "Podplacený rozhodčí", emoji: "🤝",  amount: -1200 },
      { index: 8,  type: "chance",     label: "Rozmary osudu",       emoji: "🎴" },
      { index: 9,  type: "coins_gain", label: "Výborná forma",       emoji: "🌿",  amount: 900 },
      { index: 10, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 11, type: "coins_lose", label: "Mokrá dráha",         emoji: "🌧️",  amount: -500 },
      { index: 12, type: "mafia",      label: "Sázkový boss",        emoji: "🎩" },
      { index: 13, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 14, type: "finance",    label: "Sázková kancelář",    emoji: "💰" },
      { index: 15, type: "coins_gain", label: "Stájový bonus",       emoji: "🎖️",  amount: 500 },
      { index: 16, type: "coins_lose", label: "Ztráta sázky",        emoji: "🎫",  amount: -700 },
      { index: 17, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 18, type: "coins_lose", label: "Zranění koně",        emoji: "🩹",  amount: -600 },
      { index: 19, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 20, type: "chance",     label: "Rozmary osudu",       emoji: "🎴" },
    ],
  },
  assets: {
    boardBgImage: "/chuchle.webp",
    centerBgImage: "/plaketa-light.webp",
  },
  racerRefs: [
    { slotIndex: 0, racer_id: "r6" },
    { slotIndex: 1, racer_id: "viento_dorado" },
    { slotIndex: 2, racer_id: "el_relampago" },
    { slotIndex: 3, racer_id: "caballo_real" },
    { slotIndex: 4, racer_id: "horse_classic_pablo" },
  ],
  /** @fallback inline data — seed source + runtime fallback pokud registry není dostupná */
  racers: [
    {
      "id": "viento_dorado",
      "name": "Hogo fogo",
      "speed": 3,
      "price": 1500,
      "emoji": "🟤",
      "maxStamina": 100,
      "flavorText": "Umí zabrat, ale i shodit jezdce!",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/viento_dorado.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 1
    },
    {
      "id": "el_relampago",
      "name": "Křemešník",
      "speed": 4,
      "price": 2000,
      "emoji": "⚡",
      "maxStamina": 90,
      "flavorText": "Veterán závodního okruhu, co ještě nepůjde do salámu.",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/el_relampago.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 2
    },
    {
      "id": "caballo_real",
      "name": "Královský hřebec",
      "speed": 5,
      "price": 3500,
      "emoji": "👑",
      "maxStamina": 100,
      "flavorText": "Kůň s královskou výdrží.",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/caballo_real.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 3
    },
    {
      "id": "horse_classic_pablo",
      "name": "Pablo",
      "speed": 7,
      "price": 4500,
      "emoji": "🐴",
      "maxStamina": 78,
      "image": "/themes/_shared/racer-horse_classic_pablo.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 4
    },
    {
      "id": "zeleznik",
      "name": "Železník",
      "speed": 10,
      "price": 99999,
      "emoji": "🐴",
      "maxStamina": 10,
      "isLegendary": true,
      "flavorText": "Železník — legendární kůň, který nezná strach, únavu ani druhé místo. Jeho jediný cíl je jasný: vyhrát.",
      "image": "/themes/_shared/racer-zeleznik.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 5
    },
    {
      "id": "r6",
      "name": "Pepík",
      "speed": 4,
      "price": 2500,
      "emoji": "🐴",
      "maxStamina": 100,
      "flavorText": "Pepó! Pepane! Pepíku!!",
      "image": "/themes/_shared/racer-r6.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 0
    }
  ],
  mapMeta: {
    yearStart: 1921,
    place: "Velká Chuchle, Praha",
    subtitle: "Tradice na tribuně, nervy ve stáji.",
  },
};
