import type { Theme } from ".";

export const horseClassicTheme: Theme = {
  id: "horse-classic",
  name: "Velká Chuchle",
  description: "Závodní dráha Velké Chuchle, rok 1930. Tradice, trávník a koňský osud.",
  isPaid: false,
  priceCzk: 0,
  cardThemeTag: "horse",
  colors: {
    pageBackground:     "bg-amber-50",
    cardBackground:     "bg-amber-50",
    boardSurface:       "bg-green-700/80",
    boardSurfaceBorder: "border-green-900",
    centerBackground:   "bg-transparent",
    centerBorder:       "border-green-600/0",
    centerTitle:        "text-stone-900",
    centerSubtitle:          "text-stone-700",
    centerDescriptionPill:   "inline-block rounded-md px-2 py-0.5 bg-amber-50/80 border border-stone-400/40 text-stone-800",
    fieldStyles: {
      start:      "h-20 w-20 border-emerald-900 bg-emerald-800 text-amber-200",
      coins_gain: "h-[72px] w-[72px] border-green-600 bg-amber-100 text-green-900",
      coins_lose: "h-[72px] w-[72px] border-red-400 bg-red-100 text-red-900",
      gamble:     "h-[72px] w-[72px] border-purple-500 bg-purple-100 text-purple-900",
      racer:      "h-[72px] w-[72px] border-amber-600 bg-amber-200 text-amber-900",
      horse:      "h-[72px] w-[72px] border-amber-600 bg-amber-200 text-amber-900",
      neutral:    "h-[72px] w-[72px] border-stone-400 bg-stone-100 text-stone-700",
      chance:     "h-[72px] w-[72px] border-green-600 bg-green-100 text-green-900",
      finance:    "h-[72px] w-[72px] border-amber-600 bg-amber-100 text-amber-900",
      mafia:      "h-[72px] w-[72px] border-stone-500 bg-stone-200 text-stone-800",
    },
    activePlayerBadge: "bg-green-900 text-amber-200",
    rollPanelIdle:     "bg-amber-100",
    rollPanelRolling:  "bg-green-100",
    textPrimary:       "text-stone-800",
    textMuted:         "text-stone-700",
    playerCardActive:  "border-green-700 bg-green-50 shadow-sm",
    playerCardNormal:  "border-stone-300 bg-amber-50",
    playerCardHover:   "border-amber-500 bg-amber-100 shadow-sm",
    arenaGradient:     "radial-gradient(ellipse 140% 90% at 50% 50%, #f0fdf4 0%, #dcfce7 30%, #d1fae5 60%, #bbf7d0 100%)",
  },
  labels: {
    themeName:      "Velká Chuchle",
    centerTitle:    "Velká Chuchle",
    centerSubtitle: "Praha, 1921. Kdo má nejlepšího koně?",
    legend: {
      gain:   "Dostihový bonus",
      lose:   "Výdaj stáje",
      gamble: "Sázka",
      racer:  "Kůň",
    },
    racer:       "Kůň",
    racers:      "Koně",
    racerField:  "Stáj",
    racingEmoji: "🐎",
  },
  board: {
    id: "small-stadium",
    shape: "stadium",
    fieldCount: 21,
    racerSlotIndexes: [3, 10, 17, 19],
    fields: [
      { index: 0,  type: "start",      label: "Start / Cíl",         emoji: "🏁",  amount: 1000 },
      { index: 1,  type: "mafia",      label: "Záhadný mecenáš",     emoji: "🎩",  amount: 50 },
      { index: 2,  type: "coins_lose", label: "Veterinář",           emoji: "🩺",  amount: -600 },
      { index: 3,  type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 4,  type: "coins_gain", label: "Vítěz dostihu",       emoji: "🏆",  amount: 1500 },
      { index: 5,  type: "coins_lose", label: "Závodní poplatky",    emoji: "🏛️",  amount: -800 },
      { index: 6,  type: "coins_gain", label: "Zlaté podkůvky",      emoji: "🥇",  amount: 800 },
      { index: 7,  type: "coins_lose", label: "Podplacený rozhodčí", emoji: "🤝",  amount: -1200 },
      { index: 8,  type: "chance",     label: "Rozmary osudu",       emoji: "🎴" },
      { index: 9,  type: "coins_gain", label: "Výborná forma",       emoji: "🌿",  amount: 900 },
      { index: 10, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 11, type: "coins_lose", label: "Mokrá dráha",         emoji: "🌧️",  amount: -500 },
      { index: 12, type: "mafia",      label: "Sázkový boss",        emoji: "🎩" },
      { index: 13, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 14, type: "finance",    label: "Sázková kancelář",    emoji: "💰" },
      { index: 15, type: "chance",     label: "Šance",               emoji: "🎲" },
      { index: 16, type: "coins_lose", label: "Ztráta sázky",        emoji: "🎫",  amount: -700 },
      { index: 17, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 18, type: "coins_lose", label: "Zranění koně",        emoji: "🩹",  amount: -600 },
      { index: 19, type: "racer",      label: "Závodník",            emoji: "🐎" },
      { index: 20, type: "chance",     label: "Rozmary osudu",       emoji: "🎴" },
    ],
  },
  assets: {
    boardBgImage: "/chuchle.webp",
    centerBgImage: "/plaketa-light.webp",
  },
  racerRefs: [
    { slotIndex: 0, racer_id: "r6" },
    { slotIndex: 1, racer_id: "viento_dorado" },
    { slotIndex: 2, racer_id: "el_relampago" },
    { slotIndex: 3, racer_id: "caballo_real" },
    { slotIndex: 4, racer_id: "horse_classic_pablo" },
  ],
  /** @fallback inline data — seed source + runtime fallback pokud registry není dostupná */
  racers: [
    {
      "id": "viento_dorado",
      "name": "Hogo fogo",
      "speed": 3,
      "price": 1500,
      "emoji": "🟤",
      "maxStamina": 100,
      "flavorText": "Umí zabrat, ale i shodit jezdce!",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/viento_dorado.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 1
    },
    {
      "id": "el_relampago",
      "name": "Křemešník",
      "speed": 4,
      "price": 2000,
      "emoji": "⚡",
      "maxStamina": 90,
      "flavorText": "Veterán závodního okruhu, co ještě nepůjde do salámu.",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/el_relampago.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 2
    },
    {
      "id": "caballo_real",
      "name": "Královský hřebec",
      "speed": 5,
      "price": 3500,
      "emoji": "👑",
      "maxStamina": 100,
      "flavorText": "Kůň s královskou výdrží.",
      "image": "https://zyiaettnrfjzwcrumgty.supabase.co/storage/v1/object/public/racers/caballo_real.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 3
    },
    {
      "id": "horse_classic_pablo",
      "name": "Pablo",
      "speed": 7,
      "price": 4500,
      "emoji": "🐴",
      "maxStamina": 78,
      "flavorText": "Závodí s elegancí. Dech si hlídá sám.",
      "image": "/themes/_shared/racer-horse_classic_pablo.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 4
    },
    {
      "id": "zeleznik",
      "name": "Železník",
      "speed": 10,
      "price": 99999,
      "emoji": "🐴",
      "maxStamina": 10,
      "isLegendary": true,
      "flavorText": "Železník — legendární kůň, který nezná strach, únavu ani druhé místo. Jeho jediný cíl je jasný: vyhrát.",
      "image": "/themes/_shared/racer-zeleznik.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 5
    },
    {
      "id": "r6",
      "name": "Pepík",
      "speed": 4,
      "price": 2500,
      "emoji": "🐴",
      "maxStamina": 100,
      "flavorText": "Pepó! Pepane! Pepíku!!",
      "image": "/themes/_shared/racer-r6.webp",
      "isBuiltIn": true,
      "racerType": "horse",
      "slotIndex": 0
    }
  ],
  mapMeta: {
    yearStart: 1930,
    place: "Velká Chuchle, Praha",
    subtitle: "Tradice na tribuně, nervy ve stáji.",
  },
  content: {
    cards: {
      chance: [
        {
          id: "chuchle_chance_1",
          type: "chance",
          text: "Hodně budeš někde. Teď konkrétně ve třetí zatáčce.",
          effect: { kind: "move", value: 3 },
          effectLabel: "+3 pole",
        },
        {
          id: "chuchle_chance_2",
          type: "chance",
          text: "Tady vidím velký špatný. A taky špatný směr.",
          effect: { kind: "move", value: -2 },
          effectLabel: "-2 pole",
        },
        {
          id: "chuchle_chance_3",
          type: "chance",
          text: "Kůň ti něco říká. Dneska výjimečně poslouchej.",
          effect: { kind: "move", value: 2 },
          effectLabel: "+2 pole",
        },
        {
          id: "chuchle_chance_4",
          type: "chance",
          text: "Ajéjé. Tohle nebyl cval, to byl omyl.",
          effect: { kind: "skip_turn" },
          effectLabel: "Vynecháš tah",
        },
        {
          id: "chuchle_chance_5",
          type: "chance",
          text: "Budoucnost je mlhavá. Chuchle taky.",
          effect: { kind: "move", value: -1 },
          effectLabel: "-1 pole",
        },
        {
          id: "chuchle_chance_6",
          type: "chance",
          text: "Karty říkají: přidej. Kůň říká: pomalu.",
          effect: { kind: "move", value: 1 },
          effectLabel: "+1 pole",
        },
        {
          id: "chuchle_chance_7",
          type: "chance",
          text: "Vidím v tobě vítěze. Jenom trochu dál od cíle.",
          effect: { kind: "move", value: -3 },
          effectLabel: "-3 pole",
        },
        {
          id: "chuchle_chance_8",
          type: "chance",
          text: "Tady bude velký rychlý. Překvapivě u tebe.",
          effect: { kind: "move", value: 4 },
          effectLabel: "+4 pole",
        },
        {
          id: "ch13",
          type: "chance",
          text: "Začíná aukce o vzácného závodníka.",
          effect: { kind: "racer_auction" },
          effectLabel: "🔨 Aukce",
          imagePath: "/themes/_shared/card-aukce.webp",
        },
        {
          id: "chuchle_chance_9",
          type: "chance",
          text: "Ze dna se můžeš vytáhnout. Nejdřív ale slez z koně.",
          effect: { kind: "skip_turn" },
          effectLabel: "Vynecháš tah",
        },
        {
          id: "chuchle_chance_10",
          type: "chance",
          text: "Kartářka zamíchala karty tak rychle, že se pole posunula sama.",
          effect: { kind: "move", value: 2 },
          effectLabel: "+2 pole",
        },
        {
          id: "chuchle_chance_11",
          type: "chance",
          text: "Vidím tam zatáčku, koně a tvoje ego. Dvě z toho právě havarovalo.",
          effect: { kind: "move", value: -2 },
          effectLabel: "-2 pole",
        },
        {
          id: "chuchle_chance_12",
          type: "chance",
          text: "Tohle není smůla. To je osud v jezdeckých botách.",
          effect: { kind: "skip_turn" },
          effectLabel: "Vynecháš tah",
        },
        {
          id: "chuchle_restart_2",
          type: "chance",
          text: "Na tribuně ještě hraje hudba první republiky. Na chvíli věříš, že bude dobře.",
          effect: { kind: "move", value: 2 },
          effectLabel: "+2 pole",
        },
      ],
      finance: [
        {
          id: "chuchle_finance_1",
          type: "finance",
          text: "Zavřete oči, odcházím… s tvojí peněženkou.",
          effect: { kind: "coins", value: -600 },
          effectLabel: "-600 💰",
        },
        {
          id: "chuchle_finance_2",
          type: "finance",
          text: "Pražský sázkař ti poradil favorita. Tentokrát měl překvapivě pravdu.",
          effect: { kind: "coins", value: 900 },
          effectLabel: "+900 💰",
        },
        {
          id: "chuchle_finance_3",
          type: "finance",
          text: "Berní úřad se ozval dřív než štěstí.",
          effect: { kind: "coins", value: -800 },
          effectLabel: "-800 💰",
        },
        {
          id: "chuchle_finance_4",
          type: "finance",
          text: "Noviny píšou o krizi v Evropě. Ty zatím řešíš, čím zaplatíš krmení.",
          effect: { kind: "coins", value: -700 },
          effectLabel: "-700 💰",
        },
        {
          id: "chuchle_finance_5",
          type: "finance",
          text: "Někdo u výčepu ti poradil vítěze. Překvapivě to nebyl nesmysl.",
          effect: { kind: "coins", value: 900 },
          effectLabel: "+900 💰",
        },
        {
          id: "chuchle_finance_6",
          type: "finance",
          text: "Stájník chce zaplatit hned. Prý na dobré časy už nečeká.",
          effect: { kind: "coins", value: -500 },
          effectLabel: "-500 💰",
        },
        {
          id: "chuchle_finance_8",
          type: "finance",
          text: "Banka ti připomněla, že nový začátek se dá taky úročit.",
          effect: { kind: "coins", value: -900 },
          effectLabel: "-900 💰",
        },
        {
          id: "chuchle_finance_9",
          type: "finance",
          text: "Dostihové noviny tě zmínily mezi nadějemi sezóny. Sponzor poslal zálohu.",
          effect: { kind: "coins", value: 1000 },
          effectLabel: "+1000 💰",
        },
        {
          id: "chuchle_finance_10",
          type: "finance",
          text: "Rok 1933 přeje opatrným. Ty jsi vsadil na koně.",
          effect: { kind: "coins", value: -600 },
          effectLabel: "-600 💰",
        },
        {
          id: "chuchle_finance_11",
          type: "finance",
          text: "Vidím peníze. Ale nejsou tvoje.",
          effect: { kind: "coins", value: -700 },
          effectLabel: "-700 💰",
        },
        {
          id: "chuchle_finance_12",
          type: "finance",
          text: "Kartářka řekla, že přijde bohatství. Přišel účet za seno.",
          effect: { kind: "coins", value: -500 },
          effectLabel: "-500 💰",
        },
        {
          id: "chuchle_restart_1",
          type: "finance",
          text: "Našel jsi levné ustájení za Prahou. Není to Amerika, ale je to začátek.",
          effect: { kind: "coins", value: -500 },
          effect2: { kind: "move", value: 2 },
          effectLabel: "-500 💰 / +2 pole",
        },
        {
          id: "chuchle_restart_3",
          type: "finance",
          text: "Předválečná Evropa znervóznila investory. Tvůj sponzor se rozmyslel.",
          effect: { kind: "coins", value: -1000 },
          effectLabel: "-1000 💰",
        },
        {
          id: "chuchle_restart_5",
          type: "finance",
          text: "V lóži se usmála filmová hvězda. Sponzoři si najednou všimli i tebe.",
          effect: { kind: "coins", value: 800 },
          effectLabel: "+800 💰",
        },
      ],
      mafia: [
        {
          id: "chuchle_mafia_slot_1",
          type: "finance",
          text: "Víte, co je horší než prohrát? Platit poplatek za prohru.",
          effect: { kind: "coins", value: -700 },
          effectLabel: "-700 💰",
        },
        {
          id: "chuchle_mafia_slot_2",
          type: "finance",
          text: "Stará Chuchle má svá pravidla. Dnes jsi je porušil.",
          effect: { kind: "coins", value: -600 },
          effectLabel: "-600 💰",
        },
        {
          id: "chuchle_mafia_slot_3",
          type: "finance",
          text: "Nečekaný výběrčí u vrat. Prý je to zvyk zdejší tribuny.",
          effect: { kind: "coins", value: -500 },
          effectLabel: "-500 💰",
        },
        {
          id: "chuchle_mafia_slot_4",
          type: "finance",
          text: "Pán v melónu ti tiše podal obálku. Překvapivě s penězi uvnitř.",
          effect: { kind: "coins", value: 800 },
          effectLabel: "+800 💰",
        },
      ],
    },
  },
};
